disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
included: # paths to include during linting. `--path` is ignored if present.
  - Budget
  - Domain
  - Platform

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Budget/R.generated.swift

reporter: "xcode" 